### ISSUE TITLE
Feature Request: Option to ignore pinned tabs

### ISSUE THREAD

**Issue by bamapookie** [jdhayford/acid-tabs-extension#24] opened 2021-12-09 13:58 UTC
I have a few tabs that are pinned, and they get unpinned and added to a group .  I would like an option that would allow these pns to be ignored with grouping.

Thanks.

**Comment by jimmesamme** [comment] 2022-02-25 17:18
This would be a great enhancement IMO

**Comment by shoichiaizawa** [comment] 2022-02-25 18:14
This issue is a duplicate of #2. One of them should be closed.

**Comment by shoichiaizawa** [comment] 2022-02-25 18:40
I like Acid Tabs for its simple UI and it is OSS.
But it lacks a feature to ignore pinned tabs and this is indispensable to me.

I just found an alternative extension called [Tab Grouping Rules](https://chrome.google.com/webstore/detail/tab-groups-extension/nplimhmoanghlebhdiboeellhgmgommi) ignoring pinned tabs, plus this is a bit more feature-rich.
One downside of this for me is closed source, otherwise this almost perfectly fits my needs. Highly recommended.

As for Acid Tabs, I wait until the ignoring pinned tabs feature becomes a thing.

**Closed** 2022-02-26 12:30 UTC
